version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=your-secret-key-here
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: 
      context: ./FE
      dockerfile: Dockerfile
    volumes:
      - ./FE:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend 